Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Dal;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class AdministratorController : Controller
    {
        // GET: Administrator
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddPerson(User usr)
        {
            //if (Session["Administrator"] != null)
            //    return RedirectToAction("Login");


            dal dal = new dal();

            if (usr.Id != null)
            {
                List<User> userslist = (from u in dal.Users
                                        where (u.mode == true)
                                        select u).ToList<User>();
                User find = userslist.FirstOrDefault(x => x.Id == usr.Id);
                if (find == null)
                {
                    usr.mode =true;
                   
                    dal.Users.Add(usr);
                    dal.SaveChanges();
                    ViewBag.message13 = "User Added Successfully! ";
                    ViewBag.message14 = "Course Added Successfully! ";
                    ModelState.Remove("Id");
                    ModelState.Remove("Name");
                    ModelState.Remove("Birthday");
                    ModelState.Remove("Phone");
                    ModelState.Remove("UserName");
                    ModelState.Remove("Password");
                    ModelState.Remove("UserType");
                   
                }
                else
                {
                    ViewBag.message13 = "Invalid Person ID, This Id is Taken.";
                    return View("AddPerson");
                }
            }

            return View("AddPerson");
        }

        public ActionResult AssignStudentCourse(Grades grade)
        {
            dal dal = new dal();
            ViewBag.success2 = "";
            List<Course> coursesName = (from u in dal.Courses //gives all courses name
                                        where (u.mode == true)
                                        select u).ToList<Course>();
            if (grade != null)//if object is null because no id input
            {
                List<User> userslist = (from u in dal.Users //find if there such user
                                        where (u.Id == grade.StudentId && u.mode == true && u.UserType == "Student")
                                        select u).ToList<User>();
                if (userslist.Count > 0) //check if there is a user
                {
                    List<Grades> gradesList = (from u in dal.Grades//give all grade table list
                                               where (u.mode == true)
                                               select u).ToList<Grades>();

                    List<Course> courseidSelectedList = (from u in dal.Courses //gives selected course
                                                      where (u.Id == grade.CourseId && u.mode == true)
                                                      select u).ToList<Course>();

                    //string coursHour = courseidSelectedList[0].Hours;

                    List<int> userCourses = (from u in dal.Grades //gives All courses that studeny teach
                                                         where (u.StudentId == grade.StudentId && u.mode == true)
                                                         select u.CourseId).ToList<int>();


                    bool flagStudentHour = false; 
                    //IF THIS STUDENT TAKES OTHER COURSES AT SAME TIME

                    for (int i=0; i<userCourses.Count;i++)
                    {
                        int currtentId= userCourses[i];
                        List<Course> currentcourse = (from u in dal.Courses //gives All courses that studeny teach
                                         where (u.Id == currtentId && u.mode == true)
                                         select u).ToList<Course>();



                        int temphour = int.Parse(currentcourse[0].Hours);
                        string tempDay = currentcourse[0].Day;
                        int d2 = Convert.ToInt32(courseidSelectedList[0].Hours);

                        if (tempDay== courseidSelectedList[0].Day)
                        { 
                        if (temphour== d2 || temphour == d2+1 || temphour == d2 + 2 || temphour+1 == d2  || temphour+2 == d2  )
                        { 
                            //    if (   temphour == int.Parse(courseidSelectedList[0].Hours) && courseidSelectedList[0].Day==) 
                            flagStudentHour = true;
                        }
                        }
                    }


                    //int courseidSelected = courseidSelectedList.FirstOrDefault();

                    //List<string> studentSelected = (from u in dal.Grades
                    //                                where (u.StudentId == grade.StudentId && u.mode == true)
                    //                                select u.StudentId).ToList<string>();

                    //List<string> studentCourses = (from u in dal.Grades
                    //                               where (u.StudentId == grade.StudentId && u.CourseId == courseidSelected && u.mode == true)
                    //                               select u.StudentId).ToList<string>();

                    if(flagStudentHour)
                    {

                        ViewBag.Error = "FAILED! This Student Alread Learn other course at this TIME!";


                    }


                    if (!flagStudentHour)
                    {
                        grade.CourseId = Convert.ToInt32(courseidSelectedList[0].Id);
                        grade.Grade = 0;
                        grade.GradeA = "Grade A is Not Given Yet";
                        grade.GradeB = "GradeB Not Given Yet";
                        grade.mode = true;

                        dal.Grades.Add(grade);
                        dal.SaveChanges();
                        ViewBag.success2 = "Student assigned to the course successfuly";
                        ModelState.Remove("GradeA");
                        ModelState.Remove("GradeB");


                    }
                    //else if (studentCourses.Count >= 1) ViewBag.Error = "The Student have this course already";
                    //else ViewBag.Error = "The Student have 2 courses already";
                  
                }
                else ViewBag.Error = "No such student, add the student first";
            }

            ViewBag.CoursesList = coursesName;
            return View("AssignStudentCourse");
           
        }
        public ActionResult AddCourse(Course crs)
        {
            dal dal1 = new dal();

            if (crs.ClassRoom != null)
            {
                List<Course> courseslist = (from u in dal1.Courses
                                            where (u.mode == true)
                                            select u).ToList<Course>();

                List<string> lecturerList = (from u in dal1.Users
                                             where (u.UserType == "Lecturer")
                                             select u.Id).ToList<string>();

                bool hasLecturer = false;

                for (int i = 0; i < lecturerList.Count; i++)
                {
                    if (crs.LecId == lecturerList[i])
                        hasLecturer = true;

                }


                if (hasLecturer == false)  // IF not LECTURER
                {
                    ViewBag.message13 = "This Person is Not Lecturer! Cant Assign Coursr.";
                    return View("AddCourse");
                }

                Course find = courseslist.FirstOrDefault(x => x.Id == crs.Id); // IF there IS THIS COURSe ALREady
                bool flagMoad = false;
                bool flagClassroom = false;



                List<Course> courseslistDays = (from u in dal1.Courses      // ALL COURSES THAT IN THIS DAY
                                                where (u.mode == true )
                                                select u).ToList<Course>();

                List<Course> courseslistLec = (from u in dal1.Courses      // ALL COURSES THAT IN THIS DAY
                                                where (u.mode == true && u.LecId==crs.LecId)
                                                select u).ToList<Course>();

                bool flagLecturer = false;


                for (int i = 0; i < courseslistDays.Count; i++)       // CHeck
                {

                    if((courseslistDays[i].Day == crs.Day) && (courseslistDays[i].ClassRoom == crs.ClassRoom )&& ( ( int.Parse(courseslistDays[i].Hours) == int.Parse(crs.Hours)) || (int.Parse(courseslistDays[i].Hours) == int.Parse(crs.Hours)+1) || (int.Parse(courseslistDays[i].Hours) == int.Parse(crs.Hours)+2) || (int.Parse(courseslistDays[i].Hours) == int.Parse(crs.Hours) -1)  || (int.Parse(courseslistDays[i].Hours) == int.Parse(crs.Hours) - 2)))
                        flagClassroom = true;
                
                }


                for(int i=0;i< courseslistLec.Count;i++)
                { 
                if (courseslistLec[i].Day == crs.Day)
                {

Views/Administrator/AddCourse.cshtml

@model WebApplication3.Models.Course
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddCourse</title>
    @*<style>
            goBackCss {
                border-color: $blue;
                color: #fff;
                box-shadow: 0 0 40px 40px $blue inset, 0 0 0 0 $blue;
                transition: all 150ms ease-in-out;
                /*hover
            {
                box-shadow: 0 0 10px 0 $blue inset, 0 0 10px 4px $blue;
            }*/
        </style>*@
    <style>
        html {
            background-image: url('/Images/sea-edge-79ab30e2.png');
            background-size: cover;
        }
    </style>
</head>
<body>
    <div>



        @Html.ActionLink("Go Back", "Index", "Home")
        <h1 style="color:red"> Add Course  </h1><br />
        @using (Html.BeginForm("AddCourse", "Administrator", FormMethod.Post))
        {
            <table>
                <tr>
                    <td>Course Id: </td>
                    <td>@Html.TextBoxFor(t => t.Id) @Html.ValidationMessageFor(t => t.Id)</td>
                </tr>
                <tr>
                    <td>Course Name: </td>
                    <td>@Html.TextBoxFor(t => t.Name) @Html.ValidationMessageFor(t => t.Name)</td>
                </tr>
                <tr>
                    <td>Points: </td>
                    <td>@Html.TextBoxFor(t => t.Points) @Html.ValidationMessageFor(t => t.Points)</td>
                </tr>
                <tr>
                    <td>Lecturer Id: </td>
                    <td>@Html.TextBoxFor(t => t.LecId) @Html.ValidationMessageFor(t => t.LecId)</td>
                </tr>
                <tr>
                    <td>Lecture's Start Hour [From 8.00 to 19.00]</td>

                    <td>@Html.TextBoxFor(t => t.Hours) @Html.ValidationMessageFor(t => t.Hours)</td>
                </tr>
                <tr>
                    @*<td>Day: </td>
                    <td>@Html.TextBoxFor(t => t.Day) @Html.ValidationMessageFor(t => t.Day)</td>*@
                    <script>
                    @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    listItems.Add(new SelectListItem { Text = "Sunday", Value = "Sunday" });
                    listItems.Add(new SelectListItem { Text = "Monday", Value = "Monday" });
                    listItems.Add(new SelectListItem { Text = "Tuesday", Value = "Tuesday" });
                    listItems.Add(new SelectListItem { Text = "Wednsday", Value = "Wednsday" });
                    listItems.Add(new SelectListItem { Text = "Thursday", Value = "Thursday" });
                    listItems.Add(new SelectListItem { Text = "Friday", Value = "Friday" });
                }
                    </script>
                    <td> Day:</td>

                    <td>  @Html.DropDownListFor(t => t.Day, listItems, "select Day")</td>



                </tr>
                <tr>
                    <td>Class Room: </td>
                    <td>@Html.TextBoxFor(t => t.ClassRoom) @Html.ValidationMessageFor(t => t.ClassRoom)</td>
                </tr>
                <tr>

                    <td>MoadA: </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.TextBoxFor(t => t.MoadA, "{0:d}", new { type = "date" })
                                @Html.ValidationMessageFor(t => t.MoadA, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>MoadB: </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.TextBoxFor(t => t.MoadB, "{0:d}", new { type = "date" })
                                @Html.ValidationMessageFor(t => t.MoadB, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                </tr>

                @*<tr>
                    <td>Birthday: </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.Birthday, "{0:yyyy-MM-dd}", new { @class = "form-control", Type = "datetime-local" })
                                @Html.ValidationMessageFor(m => m.Birthday, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                </tr>

                <tr>
                    @{
                        List<SelectListItem> listItems = new List<SelectListItem>();
                        listItems.Add(new SelectListItem { Text = "Student", Value = "Student" });
                        listItems.Add(new SelectListItem { Text = "Admin", Value = "Administrator" });
                        listItems.Add(new SelectListItem { Text = "Lecturer", Value = "Lecturer" });
                    }
                    <td>Role: </td>
                    <td>@Html.DropDownListFor(m => m.UserType, listItems, "select Role")</td>

                </tr>*@

                <tr>

                    <td><input id="Submit4" name="Submit" type="submit" value="Insert" /></td>
                </tr>
            </table>
        }

        <p>
            <div style="color:red">@ViewBag.message13</div>
        </p>
    </div>

    </body>

</html>

Views/Administrator/AddPerson.cshtml

@model WebApplication3.Models.User
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddPerson</title>
    <style>
        html {
            background-image: url('/Images/sea-edge-79ab30e2.png');
            background-size: cover;
        }
    </style>
</head>
<body>
    <div>
        @*//???????*@
        @if (Session["Administrator"] == null)
        {
            <a href="@Url.Action("Index","Home")" type="submit" class="lnkbtn lnkbtn_2 Rectangle">I'm new here</a>}
        @*<a href="@Url.Action("Index", "Home")" type="submit" class="lnkbtn lnkbtn_2 Rectangle">I'm new here</a*@>



        @Html.ActionLink("Go Back", "Index", "Home")
        <h1 style="color:red"> Add Person  </h1><br />
        @using (Html.BeginForm("AddPerson", "Administrator", FormMethod.Post))
        {
            <table>
                <tr>
                    <td>Id: </td>
                    <td>@Html.TextBoxFor(m => m.Id) @Html.ValidationMessageFor(x => x.Id)</td>
                </tr>
                <tr>
                    <td>Name: </td>
                    <td>@Html.TextBoxFor(m => m.Name) @Html.ValidationMessageFor(x => x.Name)</td>
                </tr>
                <tr>
                    <td>Birthday: </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @*@Html.TextBoxFor(m => m.Birthday, "{0:yyyy-MM-dd}", new { @class = "form-control", Type = "datetime-local" })*@
                                @Html.TextBoxFor(m => m.Birthday, "{0:d}", new { type = "date" })
                                @Html.ValidationMessageFor(m => m.Birthday, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Phone: </td>
                    <td>@Html.TextBoxFor(m => m.Phone) @Html.ValidationMessageFor(x => x.Phone)</td>
                </tr>
                <tr>
                    <td>User Name: </td>
                    <td>@Html.TextBoxFor(m => m.UserName) @Html.ValidationMessageFor(x => x.UserName)</td>
                </tr>
                <tr>
                    <td>Password: </td>
                    <td>@Html.TextBoxFor(m => m.Password) @Html.ValidationMessageFor(x => x.Password)</td>
                </tr>
                <tr>
                    @{
                        List<SelectListItem> listItems = new List<SelectListItem>();
                        listItems.Add(new SelectListItem { Text = "Student", Value = "Student" });
                        listItems.Add(new SelectListItem { Text = "Admin", Value = "Administrator" });
                        listItems.Add(new SelectListItem { Text = "Lecturer", Value = "Lecturer" });
                    }
                    <td>Role: </td>
                    <td>@Html.DropDownListFor(m => m.UserType, listItems, "select Role")</td>

                </tr>

                <tr>

                    <td><input id="Submit4" name="Submit" type="submit" value="Insert" /></td>
                </tr>
            </table>
        }

        <p>
            <div style="color:red">@ViewBag.message13</div>
        </p>
    </div>
                        }
</body>
</html>

Views/Administrator/AssignStudentCourse.cshtml
@model WebApplication3.Models.Grades
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AssignStudentCourse</title>
    <style>
        html {
            background-image: url('/Images/sea-edge-79ab30e2.png');
            background-size: cover;
        }
    </style>
</head>
<body>
    <div>
        <h1 style="color:red"> Assign Student to Course  </h1><br />
        @Html.ActionLink("Go Back", "Index", "Home")
        <table>
            @using (Html.BeginForm("AssignStudentCourse", "Administrator", FormMethod.Post))
            {
                <tr>
                    <td>ID: </td>
                    <td>
                        @Html.TextBoxFor(m => m.StudentId) @Html.ValidationMessageFor(x => x.StudentId)
                    </td>
                    @Html.DropDownListFor(y => y.CourseId, new SelectList(ViewBag.CoursesList, "Id", "Name"), "select Course")
                    <td><input id="Submit5" name="Submit" type="submit" value="Assign" /></td>
                    @Html.Raw(ViewBag.Error)
                    @Html.Raw(ViewBag.success2)
                </tr>
            }
        </table>
    </div>
</body>
</html>

Views/Administrator/ManageCourseSchedule.cshtml

@model WebApplication3.Models.Course
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ManageCourseSchedule</title>
    <style>
        html {
            background-image: url('/Images/sea-edge-79ab30e2.png');
            background-size: cover;
        }
    </style>
    <style>
        .button {
            display: inline-block;
            border-radius: 4px;
            background-color: #4169E1;
            border: none;
            color: #FFFFFF;
            text-align: center;
            font-size: 28px;
            padding: 20px;
            width: 200px;
            transition: all 0.5s;
            cursor: pointer;
            margin: 5px;
        }

            .button span {
                cursor: pointer;
                display: inline-block;
                position: relative;
                transition: 0.5s;
            }

                .button span:after {
                    content: '\00bb';
                    position: absolute;
                    opacity: 0;
                    top: 0;
                    right: -20px;
                    transition: 0.5s;
                }

            .button:hover span {
                padding-right: 25px;
            }

                .button:hover span:after {
                    opacity: 1;
                    right: 0;
                }
    </style>
    <style>
        a:link, a:visited {
            background-color: #4169E1;
            color: white;
            padding: 14px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
        }

        a:hover, a:active {
            background-color: darkblue;
        }
    </style>
</head>
<body>
    <div>
        <h1 style="color:red"> Manage Course Schedule </h1><br />

        @Html.ActionLink("Go Back", "Index", "Home")
        @using (Html.BeginForm("ManageCourseSchedule", "Administrator", FormMethod.Post))
        {
            <br />
            <tag>Select Course:</tag>
            @Html.DropDownListFor(y => y.Id, new SelectList(ViewBag.courseslist, "Id", "Name"), "select Course")
            <br />
            <tag>Hour:</tag>
            @Html.TextBoxFor(m => m.Hours)
            @Html.ValidationMessageFor(m => m.Hours)
            <script>
                    @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    listItems.Add(new SelectListItem { Text = "Sunday", Value = "Sunday" });
                    listItems.Add(new SelectListItem { Text = "Monday", Value = "Monday" });
                    listItems.Add(new SelectListItem { Text = "Tuesday", Value = "Tuesday" });
                    listItems.Add(new SelectListItem { Text = "Wednsday", Value = "Wednsday" });
                    listItems.Add(new SelectListItem { Text = "Thursday", Value = "Thursday" });
                    listItems.Add(new SelectListItem { Text = "Friday", Value = "Friday" });
                }
            </script>
            <br />
            <tag>Day:</tag>

            @Html.DropDownListFor(y => y.Day, listItems, "select Day")
            <br />
            <button class="button" style="vertical-align:middle"><span>Update Schedule</span></button>
            <br />
            @Html.ViewBag.success5
            @Html.ViewBag.Erro3
            @Html.ViewBag.Error4

        }

    </div>
</body>
</html>


Views/Administrator/ManageExamSchedule.cshtml
@model WebApplication3.Models.Course
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ManageExamSchedule</title>
    <style>
        html {
            background-image: url('/Images/sea-edge-79ab30e2.png');
            background-size: cover;
        }
    </style>
</head>
<body>
    <div>
        <h1 style="color:red"> Manage Exam Schedule </h1><br />
        @Html.ActionLink("Go Back", "Index", "Home")
        @using (Html.BeginForm("ManageExamSchedule", "Administrator", FormMethod.Post))
        {

                                                         <table>
                                                             <tr>
                                                                 <td>Moad A: </td>
                                                                 <td>
                                                                     <div class="form-group">
                                                                         <div class="col-md-10">
                                                                             @*@Html.TextBoxFor(m => m.Birthday, "{0:yyyy-MM-dd}", new { @class = "form-control", Type = "datetime-local" })*@
                                                                             @Html.TextBoxFor(m => m.MoadA, "{0:d}", new { type = "date" })
                                                                             @Html.ValidationMessageFor(m => m.MoadA, "", new { @class = "text-danger" })
                                                                         </div>
                                                                     </div>
                                                                 </td>
                                                             </tr>
                                                             <tr>
                                                                 <td>Moad B: </td>
                                                                 <td>
                                                                     <div class="form-group">
                                                                         <div class="col-md-10">
                                                                             @*@Html.TextBoxFor(m => m.Birthday, "{0:yyyy-MM-dd}", new { @class = "form-control", Type = "datetime-local" })*@
                                                                             @Html.TextBoxFor(m => m.MoadB, "{0:d}", new { type = "date" })
                                                                             @Html.ValidationMessageFor(m => m.MoadB, "", new { @class = "text-danger" })
                                                                         </div>
                                                                     </div>
<tr>  @Html.DropDownListFor(y => y.Name, new SelectList(ViewBag.coursesName, "Name"), "select course")</tr>
                                                             <td><input id="Submit5" name="Submit" type="submit" value="Update schedule" /></td>
                                                             <tr>@Html.ViewBag.success4</tr>
                                                             <tr>@Html.ViewBag.Error</tr>
                                                             <tr>@Html.ViewBag.Error2</tr>

                                                             @*<td><input id="Submit4" name="Submit" type="submit" value="Insert" /></td>*@
                                                             
                                                         </table>
            @*<table>
                <tr>Moad A:</tr>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.MoadA, "{0:d}", new { type = "date" })
                        @Html.ValidationMessageFor(m => m.MoadA, "", new { @class = "text-danger" })
                    </div>
                </div>

                <
                <tr>Moad B:</tr>

                <p> </p>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.MoadB, "{0:d}", new { type = "date" })
                        @Html.ValidationMessageFor(m => m.MoadB, "", new { @class = "text-danger" })
                    </div>
                </div>

                <tr>  @Html.DropDownListFor(y => y.Name, new SelectList(ViewBag.coursesName, "Name"), "select course")</tr>
                <td><input id="Submit5" name="Submit" type="submit" value="Update schedule" /></td>
                <tr>@Html.ViewBag.success4</tr>
                <tr>@Html.ViewBag.Error</tr>
                <tr>@Html.ViewBag.Error2</tr>
            </table>*@
        }
    </div>
</body>
</html>



Views/Administrator/UpdateCourseGrade.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UpdateCourseGrade</title>
    <style>
        html {
            background-image: url('/Images/sea-edge-79ab30e2.png');
            background-size: cover;
        }
    </style>
</head>
<body>
    <div>
        <h1 style="color:red"> Update Course Grade </h1><br />
        @Html.ActionLink("Go Back", "Index", "Home")
    </div>
</body>
</html>